### ISSUE TITLE
/bin/api harmony-generators

### ISSUE THREAD

**Issue by rynz** [koajs/api-boilerplate#7]
```
git clone https://github.com/koajs/api-boilerplate.git
cd api-boilerplate
npm install
chmod +x bin/api
./bin/api
```

```
/api-boilerplate/node_modules/koa-response-time/index.js:15
  return function *responseTime(next){
                  ^
SyntaxError: Unexpected token *
```

How can I run it with --harmony-generators flags?

**Comment by heshiming** [comment]
You'll need to grab nvm: https://github.com/creationix/nvm . Then `nvm install v0.11.13`, `nvm use v0.11.13`, then run `node --harmony`.

**Comment by rynz** [comment]
I understand the node --harmony flag etc - I'm wondering if it's possible to run directly from the https://github.com/koajs/api-boilerplate/blob/master/bin/api script. There doesn't seem to be a way to pass it the harmony flag.

**Comment by tj** [comment]
nope, you have to use something like the "v8-args" module to effectively wrap/proxy the executable. For now I just do `node --harmony bin/api`, that sort of idea, hopefully in the near future generators will be by default

**Comment by tj** [comment]
(we should doc ^ though, it's not clear that's for sure)

**Comment by rynz** [comment]
Okay no worries, thanks for the heads up.
